from __future__ import annotations

from collections.abc import Sequence
from typing import Protocol

from cgt_marker.core.claim import Claim
from cgt_marker.core.evidence import EvidenceRef
from cgt_marker.core.marker import MarkerDraft


class ConflictDetector(Protocol):
    """Protocol for deterministic claim-to-claim conflict detectors."""

    @property
    def name(self) -> str:
        """Human-readable detector name."""

    def detect(self, new_claim: Claim, existing_claims: Sequence[Claim]) -> list[MarkerDraft]:
        """Return marker drafts generated by comparing a claim with existing claims."""


def evidence_from_claim(claim: Claim) -> EvidenceRef:
    """Build the default evidence reference for a claim."""

    uri = claim.metadata.get("uri")
    quote = claim.metadata.get("quote")
    return EvidenceRef(
        claim_id=claim.id or None,
        source=claim.source,
        uri=uri if isinstance(uri, str) else None,
        quote=quote if isinstance(quote, str) else None,
    )
